model:
  name: tmm_module
  tim_layers: 2
  stim_layers: 2
  hidden_dim: 512
  motion_dim: 256
train:
  epochs: 40
  batch_size: 4
  lr: 1e-4
  weight_decay: 1e-5
  device: cuda
data:
  dataset: SportsMOT
  ann_file: /path/to/sportsmot/annotations.yaml
  img_dir: /path/to/sportsmot/images
  seq_len: 10